all:
  children:

    swarm_manager:
      hosts:
        pterodactyl.diesel.net:

          app_url: https://{{ inventory_hostname }}
          app_timezone: America/Los_Angeles
          app_service_author: tom@kiwi-labs.net
          trusted_proxies: '*'

          mail_from: "noreply@example.com"
          mail_driver: smtp
          mail_host: mail
          mail_port: 1025
          mail_username: ""
          mail_password: ""
          mail_encryption: True


          mysql_password: "{{ lookup('env', 'MYSQL_PASSWORD') }}"
          mysql_root_password: "{{ lookup('env', 'MYSQL_ROOT_PASSWORD') }}"

  vars:
    
    ansible_user: automation
    ansible_python_interpreter: /usr/bin/python3
