all:
  children:

    swarm_manager:
      hosts:
        pterodactyl.diesel.net:

          app_url: https://{{ inventory_hostname }}
          app_cors_allowed_origins: '*.diesel.net,*.kiwi-labs.net'
          app_timezone: America/Los_Angeles
          app_service_author: tom@kiwi-labs.net
          trusted_proxies: '*'

          mail_from: "tomdaley92@gmail.com"
          mail_driver: smtp
          mail_host: smtp.gmail.com
          mail_port: 587
          mail_username: "{{ lookup('env', 'SMTP_USERNAME') }}"
          mail_password: "{{ lookup('env', 'SMTP_PASSWORD') }}"
          mail_encryption: tls


          mysql_password: "{{ lookup('env', 'MYSQL_PASSWORD') }}"
          mysql_root_password: "{{ lookup('env', 'MYSQL_ROOT_PASSWORD') }}"

  vars:
    
    ansible_user: automation
    ansible_python_interpreter: /usr/bin/python3
