- hosts: swarm_manager
  roles:
    - application
    - traefik
  
  tasks:

    - include_role:
        name: application
        tasks_from: make_data_dir

    # - file:
    #     path: '{{ data_dir }}'
    #     owner: '472'
    #     group: '0'
    #     mode: u=rwx,g=rx
    #   become: yes

    - name: make config subdirs
      file:
        path: '{{ config_dir }}/{{ item }}'
        state: directory
        #owner: '472'
        #group: '0'
        #mode: u=rwx,g=rx
      #become: yes
      loop:
        - mysql
        - var
        - logs

    - include_role:
        name: docker
        tasks_from: stack_deploy
