- hosts: swarm_manager
  roles:
    - application
    - traefik
  
  tasks:

    - include_role:
        name: application
        tasks_from: make_data_dir

    - name: make data subdirs
      file:
        path: '{{ data_dir }}/{{ item }}'
        state: directory
      loop:
        - mysql
        - var
        - logs

    - include_role:
        name: docker
        tasks_from: stack_deploy
